version: 2
jobs:
    build:
        docker:
            - image: quay.io/pantheon-public/build-tools-ci:1.x
        working_directory: ~/working
        environment:
            BASH_ENV: ~/.bashrc
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
        steps:
            - checkout
            - run:
                name: Composer install
                command: |
                  composer remove drupal/search_api_solr --no-update
                  composer install
            - save_cache:
                key: dependency-cache-{{ checksum "composer.json" }}
                paths:
                  - ~/.composer/cache
            - run:
                name: Code linting
                command: ./vendor/bin/phpcs --report=full --standard=vendor/drupal/coder/coder_sniffer/Drupal . --ignore=vendor
