version: 2
# https://circleci.com/docs/configuration#machine
jobs:
    build:
        docker:
            - image: quay.io/pantheon-public/build-tools-ci:6.x
        working_directory: ~/working
        environment:
            BASH_ENV: ~/.bashrc
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
            TERMINUS_SITE: search-api-pantheon-d8
        steps:
            - checkout
            - run:
                name: log in
                command: |
                  git config --global user.email "$GitEmail"
                  git config --global user.name "Circle CI"
                  mkdir -p $HOME/.ssh && echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
                  terminus auth:login -n --machine-token="$TERMINUS_TOKEN"
                  terminus env:list --field=id $TERMINUS_SITE | grep -v '[a-z]' | grep -Eo '[0-9]{1,9}' | sort --numeric-sort --reverse | sed 1,7d | xargs -n1 -I ENV terminus env:delete --yes $TERMINUS_SITE.ENV

       #     - restore_cache:
       #         key: dependency-cache-{{ checksum "composer.json" }}
            - run:
                name: Composer install
                command: |
                  composer install
                  drush help

            - run:
                name: Behavioral tests
                command: |
                  export TERMINUS_ENV=$CIRCLE_BUILD_NUM
                  export SITE_ENV=$TERMINUS_SITE.$TERMINUS_ENV
                  cd .circleci
                  ./create-fresh-d8-site.sh
                  ./setup-d8-repo.sh
                  ./enable-modules.sh
                  ./verify-solr.sh


# Drupal 9 CI steps

# Update Drupal Core

# Make multidev

# Install Drupal Umami profile

# Git clone to local (CI container)

# Composer add search_api_pantheon (which should bring along everything else (search_api_solr, solarium))

# Push to pantheon multidev

# Enable modules

# Configure search

# run indexing

# do a search


